# cargo

# [[file:~/Workspace/Programming/gosh-rs/gosh/gosh.note::*cargo][cargo:1]]
[package]
name = "gosh"
version = "0.0.23"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
dotenv = "0.13"
dirs = "2"
tempfile = "3.0"
serde = "1.0"
serde_json = "1.0"
quicli = "0.4"
duct = "0.10"
nom = "4.0"
linefeed = "0.6"
structopt = "0.2"
gosh-core = { git = "https://github.com/gosh-rs/gosh-core.git" }
gosh-models = {git = "https://github.com/gosh-rs/gosh-models.git", branch="dev"}
gosh-db = {git = "https://github.com/gosh-rs/gosh-database.git", branch="dev"}
lbfgs = {git = "https://github.com/ybyygu/rust-lbfgs.git", tag="v0.0.14" }
text-parser = {git = "https://github.com/ybyygu/text-parser.git", tag="v0.0.3" }
cg_descent = {git = "https://github.com/ybyygu/cg_descent.rs" }
#gosh-core = {path = "../core"}
#gosh-models = {path = "../models"}
#gosh-adaptors = {path = "../adaptors"}
#gosh-db = {path = "../database", features = ["adhoc"] }
#
#lbfgs = {path = "/home/ybyygu/Workspace/Programming/rust-libs/lbfgs"}
#text-parser = {git = "https://github.com/ybyygu/text-parser.git", tag="v0.0.3" }
#cg_descent = {git = "https://github.com/ybyygu/cg_descent.rs" }

[dev-dependencies]
approx = "0.3"
# cargo:1 ends here
