# cargo

# [[file:~/Workspace/Programming/gosh-rs/gosh/gosh.note::*cargo][cargo:1]]
[package]
name = "gosh"
version = "0.0.24"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]
description = "Rusty framework for multiscale/multilevel modeling"
homepage = "https://github.com/gosh-rs/gosh"
repository = "https://github.com/gosh-rs/gosh"
license = "MIT OR Apache-2.0"
exclude = ["bin/*.*", "docs/*.*"]

[dependencies]
dotenv = "0.13"
dirs = "2"
tempfile = "3.0"
serde = "1.0"
serde_json = "1.0"
duct = "0.10"
nom = "4.0"
linefeed = "0.6"
structopt = "0.3"
gosh-core = "0.0.1"
gosh-model = "0.0.9"
gosh-adaptor = "0.0.4"
gosh-database = {version="0.0.7", features = ["adhoc"] }

#lbfgs = {path = "/home/ybyygu/Workspace/Programming/rust-libs/lbfgs"}
#cg_descent = {git = "https://github.com/ybyygu/cg_descent.rs" }

[dev-dependencies]
approx = "0.3"
# cargo:1 ends here
