# cargo

# [[file:~/Workspace/Programming/gosh-rs/gosh/gosh.note::*cargo][cargo:1]]
[package]
name = "gosh"
version = "0.0.21"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
dotenv = "0.13"
dirs = "2"
tempfile = "3.0"
serde = "1.0"
serde_json = "1.0"
quicli = "0.4"
duct = "0.10"
nalgebra = {version="0.18", features=["serde-serialize"]}
nom = "4.0"
linefeed = "0.6"
structopt = "0.2"
vecfx = {git = "https://github.com/gchemol/vecfx.git", tag="v0.0.4", features=["nalgebra"]}
gchemol = {git = "https://github.com/ybyygu/gchemol.git", tag="v0.0.33"}
#gchemol = {path = "/home/ybyygu/Workspace/Programming/gchemol-rs/gchemol/gchemol"}
gosh-models = {git = "https://github.com/gosh-rs/models.git", tag="v0.0.7"}
#gosh-models = {version = "*", path = "../models"}
#lbfgs = {path = "/home/ybyygu/Workspace/Programming/rust-libs/lbfgs"}
lbfgs = {git = "https://github.com/ybyygu/rust-lbfgs.git", tag="v0.0.14" }
text-parser = {git = "https://github.com/ybyygu/text-parser.git", tag="v0.0.3" }
cg_descent = {git = "https://github.com/ybyygu/cg_descent.rs" }

[dev-dependencies]
approx = "0.3"
# cargo:1 ends here
