# cargo

# [[file:~/Workspace/Programming/gosh-rs/gosh/gosh.note::*cargo][cargo:1]]
[package]
name = "gosh"
version = "0.0.24"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
dotenv = "0.13"
dirs = "2"
tempfile = "3.0"
serde = "1.0"
serde_json = "1.0"
duct = "0.10"
nom = "4.0"
linefeed = "0.6"
structopt = "0.3"
gosh-core = { version="0.0.1", path = "../core"}
gosh-models = {version="0.0.8", path = "../models"}
gosh-adaptors = {version="0.0.4", path = "../adaptors"}
gosh-db = {version="0.0.6", path = "../database", features = ["adhoc"] }

#lbfgs = {path = "/home/ybyygu/Workspace/Programming/rust-libs/lbfgs"}
#cg_descent = {git = "https://github.com/ybyygu/cg_descent.rs" }

[dev-dependencies]
approx = "0.3"
# cargo:1 ends here
