# [[file:~/Workspace/Programming/gosh/gosh.note::c45d1413-12b8-471e-b060-da682339ad4b][c45d1413-12b8-471e-b060-da682339ad4b]]
[package]
name = "gosh"
version = "0.0.6"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
quicli = "*"
linefeed = {git = "https://github.com/murarth/linefeed.git"}
#gchemol = { path = "/home/ybyygu/Workspace/Programming/gchemol" }
gchemol = { git = "https://github.com/ybyygu/gchemol.git" }
# c45d1413-12b8-471e-b060-da682339ad4b ends here
