# cargo

# [[file:~/Workspace/Programming/gosh/gosh.note::*cargo][cargo:1]]
[package]
name = "gosh"
version = "0.0.16"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
dotenv = "*"
tempfile = "*"
serde = "*"
dirs = "*"
serde_json = "*"
quicli = "0.4"
duct = "0.10"
nalgebra = "*"
nom = "4.0"
linefeed = "0.5"
structopt = "0.2"
gchemol = {path = "/home/ybyygu/Workspace/Programming/gchemol"}
lbfgs = {git = "https://github.com/ybyygu/rust-lbfgs.git" }
textparser = {path = "/home/ybyygu/Workspace/Programming/rust-libs/text-parser" }
cg_descent = {git = "https://github.com/ybyygu/cg_descent.rs" }

[dev-dependencies]
approx = "0.3"
# cargo:1 ends here
