# cargo

# [[file:~/Workspace/Programming/gosh/gosh.note::*cargo][cargo:1]]
[package]
name = "gosh"
version = "0.0.16"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
dotenv = "*"
tempfile = "*"
serde = "*"
dirs = "*"
serde_json = "*"
duct = "0.10"
nalgebra = "*"
nom = "4.0"
linefeed = "0.5"
quicli = "*"
structopt = "*"
gchemol = {git = "https://github.com/ybyygu/gchemol.git" }
#lbfgs = {git = "https://github.com/ybyygu/rust-lbfgs.git" }
lbfgs = {path = "/home/ybyygu/Workspace/Programming/rust-libs/lbfgs" }
textparser = {git = "https://github.com/ybyygu/text-parser.git" }
cg_descent = {git = "https://github.com/ybyygu/cg_descent.rs" }
#cg_descent = {path = "/home/ybyygu/Workspace/Programming/rust-libs/cg_descent.rs" }

[dev-dependencies]
approx = "0.3"
# cargo:1 ends here
