# [[file:~/Workspace/Programming/gosh/gosh.note::c45d1413-12b8-471e-b060-da682339ad4b][c45d1413-12b8-471e-b060-da682339ad4b]]
[package]
name = "gosh"
version = "0.0.7"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
approx = "*"
quicli = "*"
duct = "0.10"
nalgebra = "*"
linefeed = {git = "https://github.com/murarth/linefeed.git", rev="6ba931f" }
#linefeed = "0.5"
#gchemol = { path = "/home/ybyygu/Workspace/Programming/gchemol" }
gchemol = { git = "https://github.com/ybyygu/gchemol.git" }
# c45d1413-12b8-471e-b060-da682339ad4b ends here
