# [[file:~/Workspace/Programming/gosh/gosh.note::*cargo][cargo:1]]
[package]
name = "gosh"
version = "0.0.9"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
approx = "*"
quicli = "*"
duct = "0.10"
nalgebra = "*"
linefeed = {git = "https://github.com/murarth/linefeed.git", rev="6ba931f" }
#linefeed = "0.5"
gchemol = {rev="v0.0.21", path = "/home/ybyygu/Workspace/Programming/gchemol" }
#gchemol = {git = "https://github.com/ybyygu/gchemol.git" }

[dev-dependencies]
approx = "0.3"
# cargo:1 ends here
